:- multifile obj_map/4.
:- dynamic obj_map/4.

obj_map(g1  ,graph,  v,    low).
obj_map(g2  ,graph,  c,    low).
obj_map(g3  ,graph,  minc, low).
obj_map(g4  ,graph,  maxc, low).
obj_map(g5  ,graph,  s,    low).
obj_map(g6  ,graph,  mins, low).
obj_map(g7  ,graph,  maxs, low).
obj_map(g8  ,graph,  mina, low).
obj_map(g9  ,graph,  v,    up).
obj_map(g10 ,graph,  c,    up).
obj_map(g11 ,graph,  minc, up).
obj_map(g12 ,graph,  maxc, up).
obj_map(g13 ,graph,  s,    up).
obj_map(g14 ,graph,  mins, up).
obj_map(g15 ,graph,  maxs, up).
obj_map(g16 ,graph,  maxa, up).
obj_map(f1  ,forest, t,    low).
obj_map(f2  ,forest, f,    low).
obj_map(f3  ,forest, minf, low).
obj_map(f4  ,forest, maxf, low).
obj_map(f5  ,forest, mind, low).
obj_map(f6  ,forest, maxd, low).
obj_map(f7  ,forest, minp, low).
obj_map(f8  ,forest, maxp, low).
obj_map(f9  ,forest, mint, low).
obj_map(f10 ,forest, maxt, low).
obj_map(f11 ,forest, t,    up).
obj_map(f12 ,forest, f,    up).
obj_map(f13 ,forest, minf, up).
obj_map(f14 ,forest, maxf, up).
obj_map(f15 ,forest, mind, up).
obj_map(f16 ,forest, maxd, up).
obj_map(f17 ,forest, minp, up).
obj_map(f18 ,forest, maxp, up).
obj_map(f19 ,forest, mint, up).
obj_map(f20 ,forest, maxt, up).
obj_map(f01  ,forest0, t,    low).
obj_map(f02  ,forest0, f,    low).
obj_map(f03  ,forest0, minf, low).
obj_map(f04  ,forest0, maxf, low).
obj_map(f05  ,forest0, mind, low).
obj_map(f06  ,forest0, maxd, low).
obj_map(f07  ,forest0, minp, low).
obj_map(f08  ,forest0, maxp, low).
obj_map(f09  ,forest0, mint, low).
obj_map(f010 ,forest0, maxt, low).
obj_map(f011 ,forest0, t,    up).
obj_map(f012 ,forest0, f,    up).
obj_map(f013 ,forest0, minf, up).
obj_map(f014 ,forest0, maxf, up).
obj_map(f015 ,forest0, mind, up).
obj_map(f016 ,forest0, maxd, up).
obj_map(f017 ,forest0, minp, up).
obj_map(f018 ,forest0, maxp, up).
obj_map(f019 ,forest0, mint, up).
obj_map(f020 ,forest0, maxt, up).
obj_map(t1  ,tree, f,         low).
obj_map(t2  ,tree, mind,      low).
obj_map(t3  ,tree, maxd,      low).
obj_map(t4  ,tree, minp,      low).
obj_map(t5  ,tree, maxp,      low).
obj_map(t6  ,tree, f,         up).
obj_map(t7  ,tree, mind,      up).
obj_map(t8  ,tree, maxd,      up).
obj_map(t9  ,tree, minp,      up).
obj_map(t10 ,tree, maxp,      up).
obj_map(p1  ,partition, nval,        low).
obj_map(p2  ,partition, min,         low).
obj_map(p3  ,partition, max,         low).
obj_map(p4  ,partition, range,       low).
obj_map(p5  ,partition, sum_squares, low).
obj_map(p6  ,partition, nval,        up).
obj_map(p7  ,partition, min,         up).
obj_map(p8  ,partition, max,         up).
obj_map(p9  ,partition, range,       up).
obj_map(p10 ,partition, sum_squares, up).
obj_map(p01  ,partition0, nval,        low).
obj_map(p02  ,partition0, min,         low).
obj_map(p03  ,partition0, max,         low).
obj_map(p04  ,partition0, range,       low).
obj_map(p05  ,partition0, sum_squares, low).
obj_map(p06  ,partition0, nval,        up).
obj_map(p07  ,partition0, min,         up).
obj_map(p08  ,partition0, max,         up).
obj_map(p09  ,partition0, range,       up).
obj_map(p010 ,partition0, sum_squares, up).
obj_map(group01 ,group, ng,           low).
obj_map(group02 ,group, nv,           low).
obj_map(group03 ,group, smin,         low).
obj_map(group04 ,group, smax,         low).
obj_map(group05 ,group, srange,       low).
obj_map(group06 ,group, ssum_squares, low).
obj_map(group07 ,group, dmin,         low).
obj_map(group08 ,group, dmax,         low).
obj_map(group09 ,group, drange,       low).
obj_map(group10 ,group, dsum_squares, low).
obj_map(group11 ,group, ng,           up).
obj_map(group12 ,group, nv,           up).
obj_map(group13 ,group, smin,         up).
obj_map(group14 ,group, smax,         up).
obj_map(group15 ,group, srange,       up).
obj_map(group16 ,group, ssum_squares, up).
obj_map(group17 ,group, dmin,         up).
obj_map(group18 ,group, dmax,         up).
obj_map(group19 ,group, drange,       up).
obj_map(group20 ,group, dsum_squares, up).
obj_map(cgroup01 ,cgroup, ng,           low).
obj_map(cgroup02 ,cgroup, nv,           low).
obj_map(cgroup03 ,cgroup, smin,         low).
obj_map(cgroup04 ,cgroup, smax,         low).
obj_map(cgroup05 ,cgroup, srange,       low).
obj_map(cgroup06 ,cgroup, ssum_squares, low).
obj_map(cgroup07 ,cgroup, dmin,         low).
obj_map(cgroup08 ,cgroup, dmax,         low).
obj_map(cgroup09 ,cgroup, drange,       low).
obj_map(cgroup10 ,cgroup, dsum_squares, low).
obj_map(cgroup11 ,cgroup, ng,           up).
obj_map(cgroup12 ,cgroup, nv,           up).
obj_map(cgroup13 ,cgroup, smin,         up).
obj_map(cgroup14 ,cgroup, smax,         up).
obj_map(cgroup15 ,cgroup, srange,       up).
obj_map(cgroup16 ,cgroup, ssum_squares, up).
obj_map(cgroup17 ,cgroup, dmin,         up).
obj_map(cgroup18 ,cgroup, dmax,         up).
obj_map(cgroup19 ,cgroup, drange,       up).
obj_map(cgroup20 ,cgroup, dsum_squares, up).
